export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';
export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';
export const NEXT_SEARCH_ARTICLES = 'NEXT_SEARCH_ARTICLES';
export const FETCH_SOURCES = 'FETCH_SOURCES';
export const UPDATE_OPTIONS = 'UPDATE_OPTIONS';
export const CHANGE_COUNTRY = 'CHANGE_COUNTRY';

export const AUTHENTICATE = 'AUTHENTICATE';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';
