export const CHANGE_COUNTRY = 'CHANGE_COUNTRY';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';
export const FETCH_SOURCES = 'FETCH_SOURCES';
export const FETCH_BOOKMARKS = 'FETCH_BOOKMARKS';